### ISSUE TITLE
Remove/replace loadsac?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [giseislab/gismotools#23]
```
I propose that waveform/loadsac be either removed or reworked. It is legacy. 
loadsac bypasses scnlobjects and datasouces and does not fails inelegantly (for 
example if the desired file does not exist.) Both options are trivial, but 
deserves wider consideration. Loading SAC files is causing confusion in the 
community.

OPTION 1
Officially deprecate loadsac. Push users toward datasource/scnlobject approach. 
For dumb file loading suggest contrib/sac_file_tools/loadsacfile.m

OPTION 2
Bring contrib/sac_file_tools/loadsacfile.m inside @waveform and rename it to 
replace existing loadsac.

Thoughts? 
```

Original issue reported on code.google.com by `mew...@alaska.edu` on 17 Feb 2011 at 5:00

**Comment by gthompson** [comment]
There are so many options for loading SAC files, e.g.:

@waveform/private/load_sac.m
contributed/sac_file_tools/+sac/load.m
http://uk.mathworks.com/matlabcentral/fileexchange/46356-rdsac--read-a-sac-seismic-data-file
http://uk.mathworks.com/matlabcentral/fileexchange/5546-sacsun2mat-sacpc2mat
http://geophysics.eas.gatech.edu/people/zpeng/Teaching/MatSAC.tar.gz
http://web.utah.edu/thorne/software.html
...

Which is the best choice to wrap into @waveform?

**Comment by CelsoReyes** [comment]
Huh. somehow I missed contributed sac.  I whipped up a solution into its
own project (for the moment)

**Comment by gthompson** [comment]
This issue was moved to geoscience-community-codes/GISMO#15
