### ISSUE TITLE
Set preferences

### ISSUE THREAD

**Issue by CelsoReyes** [giseislab/gismotools#38]
Move or create preferences for appropriate values.
Implement using getpref / setpref
Related to Issue #37 

Note: as tested, getpref('WaveformSuite','UseHistory') has a 0.002s overhead.

**Comment by CelsoReyes** [comment]
The above note looks like a small amount, but adds up quickly depending on where it is used.  I've opted not to include "UseHistory" as a preference at all, since the history was ripped out of most of waveform.  

## implementing getpref / setpref:
* In order to reduce overhead, it can be wrapped in a class that reads the preference into a Const variable.  This way the value only read once, and is always available, though it will be unchangable during the session. _better when access is required everyhere and value won't change_
* Another option is to read the value into a persistent variable.  _better for when access is limited to an individual and often-called function or class and when value might change_

**Comment by gthompson** [comment]
This issue was moved to geoscience-community-codes/GISMO#26
