### ISSUE TITLE
allow shortcuts in basic math operations (+,-, .*, .^, etc) 

### ISSUE THREAD

**Issue by CelsoReyes** [giseislab/gismotools#40]
Operations run faster when I use `w.data` instead of `get(w,'data')`.
also, checking for identity operator costs very little, yet can provide decent speedup if used.

```matlab
% example, in waveform/plus
if b == 0
  return
end
a.data = a.data + b;
```

**Comment by CelsoReyes** [comment]
contraindication is that code gets a little more complex.  Only a little, though.

**Comment by gthompson** [comment]
This issue was moved to geoscience-community-codes/GISMO#28
