### ISSUE TITLE
Rip out history

### ISSUE THREAD

**Issue by CelsoReyes** [giseislab/gismotools#41]
Remove automatic history tracking from the waveform objects.

Reasoning: Bloat, processing time, and code maintainability.

**Comment by CelsoReyes** [comment]
The history-related functions still work, but I've removed the option for "Nohist" and taken history recording out of almost all base waveform functions.  (ex. add, subtract, etc.)  These changes were merged into the main when I merged the scnl_rework branch back in.

**Comment by gthompson** [comment]
This issue was moved to geoscience-community-codes/GISMO#29
