### ISSUE TITLE
Subsample for plotting

### ISSUE THREAD

**Issue by CelsoReyes** [giseislab/gismotools#43]
From Emily with response from Dane
> I would second John's thoughts about gaps, but I'm not sure I have anything 
useful to contribute to that end right now.
 
> Also, one other thing just came up. Some kind of auto-decimating just for 
plotting would be nice. I'm running up on graphics limitations with some 
500 Hz data, so being able to say plot(w,'decimate'), or something to that 
effect would be really nice! I want to keep the waveforms as they are, but 
I don't always want to wait for Matlab plot all of it just to check 
something. (I'm working on implementing something like that on my local 
copy ... I would be happy to share the code lines, if it works well enough 
... )

**Comment by gthompson** [comment]
This issue was moved to geoscience-community-codes/GISMO#31
