### ISSUE TITLE
Options for dealing with gappy data

### ISSUE THREAD

**Issue by CelsoReyes** [giseislab/gismotools#44]
From John Lyons
>Now that I have been working [...] with gappy data,
I've wondered about improving how the suite deals with gaps, or at least
building-in more options when faced with gaps (zeros, nan, large +/- number
of your choosing, other?).

**Comment by gthompson** [comment]
Some information here on how ObsPy handles missing values and overlaps:
http://docs.obspy.org/packages/autogen/obspy.core.trace.Trace.__add__.html
http://docs.scipy.org/doc/numpy/reference/maskedarray.generic.html

For waveform I think the most useful default behaviour is that if I ask for data from (say) 01:00:00 to 02:00:00, but data are missing from 01:03:35 to 01:19:57 then I should get back the number of samples I expect, but missing values are filled with NaN. (This is better than returning 2 shorter waveforms - although a w2 = w.split(NaN) method could give us this back).

But as with ObsPy I can override this (using fillgaps) to either fill with 0.0, any number of my choosing, mean, or linear interpolate between existing samples. Any of these behaviours will distort my data in some way, altering it's spectral properties and statistics. But it has to be a conscious choice by the user.

So I think this is how waveform already behaves. So the question I would have for John is what isn't working for him with the current implementation. Is better documentation needed? Is it useful to make this functionality closer to the syntax of ObsPy?

**Comment by CelsoReyes** [comment]
>For waveform I think the most useful default behaviour is that if I ask for data from (say) 01:00:00 to 02:00:00, but data are missing from 01:03:35 to 01:19:57 then I should get back the number of samples I expect, but missing values are filled with NaN. (This is better than returning 2 shorter waveforms - although a w2 = w.split(NaN) method could give us this back).

Agreed

>P.S. I'm not clear how waveform manages merges. I think syntax inspired by ObsPy like w3 = w1 + w2 is rather appealing. I think for ObsPy this works on streams (multiple traces, equivalent to a waveform vector) as well as single traces (equivalent to a single waveform object), and matching is done on network/station/channel/location.

That is something I've thought about, but have decided against because + is really a secondary-sort of concatenate.  When you read

```matlab
w3 = w1 + w2   % ex. A
w4 = w3 + 5    % ex. B
```
you would have to interpret each `+` differently.  Otherwise, ex.B could be appending the number 5 to the data in w3. 

For consistentcy's sake, I would rather be super-clear that I'm concatenating. 
For guidance, I would look toward how matlab deals with concatenations.  They have `strcat` (string concatenation), `horizcat`, vertcat` (both of which are more at the array level.
Looking at matlab's timeseries class (which might be an appropriate model), I see horizcat and vertcat (which don't make sense for waveform. who cares about horiz- or vert- in a single vector?) but I also see `addsample`, `delsample`, and `synchronize`.

of these, addsample makes the most sense. Not loving it, though.
```matlab
w3 = addsample(w1, w2)  % no likey
w3 = concat(w1,w2,[...])  % much better

% or with numbers.
w3 = addsample(w1, [1 5 3 2 9 8]) % OK. 
w3 = concat(w1, [1 5 3 2 9 8))  % also OK.
```

Man. looking at timeseries again... it is slow.. but provides so much functionality!  I wonder. could you test it's performance in the latest matlab?  The events and built-in filtering abilities are singing a siren song.

**Comment by gthompson** [comment]
This issue was moved to geoscience-community-codes/GISMO#32
