### ISSUE TITLE
Comprehensive list of GISMO functions

### ISSUE THREAD

**Issue by CelsoReyes** [giseislab/gismotools#46]
From John Lyons
> a more comprehensive list of available functions would be great. I
would often find myself digging around the web for some function or (gasp)
writing my own, but later in digging around in the actual suite functions
would find something similar or better that wasn't documented anywhere.

This corresponds to GISMO in general, I would think.

**Comment by gthompson** [comment]
This issue was moved to geoscience-community-codes/GISMO#7
