### ISSUE TITLE
Review/Remove/Edit obsolete txt files in repository

### ISSUE THREAD

**Issue by gthompson** [giseislab/gismotools#52]
EXPORT_NOTES.txt is obsolete - talks about svn. We could include some basic information for folks who still want to use svn to work with GISMO - though perhaps that is something to discourage.

INSTALL_NOTES.txt seems obsolete except there is some useful historic information there.

README.txt is obsolete. Talks about svnadmin.

contributed_style_guide.txt - very valuable and we should think about how to revise this, and whether there is alternative format that would be better (e.g. a website with some simple example code). We should probably have a similar document for Core Style Guidelines.

**Comment by CelsoReyes** [comment]
agreed.  I think I killed the README.txt in my scnl_rework branch. (which I just added)
