### ISSUE TITLE
Reorganize repository directory structure

### ISSUE THREAD

**Issue by gthompson** [giseislab/gismotools#53]
Quick suggestion:

GISMO/classes - all core classes go here (both old and new style)

GISMO/packages - any core packages go here unless they are make sense only for a single class, in which case they can go in the respective class directory

GISMO/contributed, GISMO/contributed_antelope, GISMO/contributed_internal as before, but as some point we might need to test/refactor these

Or perhaps change to:

GISMO/contributed
GISMO/contributed/antelope
GISMO/contributed/UAF (since "internal" isn't meaningful to say USF or ETHZ)
or do we need:
GISMO/external or GISMO/dependent or GISMO/thirdparty - for codes that have dependencies other than core MATLAB

startup_gismo.m - the startup file that gets called, as now

GISMO/contributed_antelope/datascope_tools should probably be migrated to a package - but would this be GISMO/packages/+datascope_tools or GISMO/contributed/antelope/+datascope_tools

What is uispecgram.m and uispecgram.fig? Do we want to keep them? Perhaps move to directory like:
GISMO/applications
or
GISMO/guis
?

**Comment by CelsoReyes** [comment]
I think that things like the uispecgram code can get put into GISMO/applications as you've suggested. 
I'm not sure I understand the breakdown between GISMO/classes and GISMO/packages.  

Also, I'm still not up to date on what contributed packages and stuff really consist of, but your suggestion to change it seems sound.  

Additional question(s):
* GISMO/dependent (dependencies other than core): how do you suggest flagging those.  For example, some stuff might require the mapping toolbox, while my spectralobject can take advantage of some other items found in the stack exchange. ( UIMAGESC,  by Frederic Moisy, downloadable from the maltabcentral fileexchange (File ID: 11368).

**Comment by gthompson** [comment]
This issue was moved to geoscience-community-codes/GISMO#4
