### ISSUE TITLE
Cannot get(scnlobject, 'station') 

### ISSUE THREAD

**Issue by gthompson** [giseislab/gismotools#56]
Error using get
Conversion to double from struct is not possible.

Error in datasource/getfilename (line 82)
	station = get(scnl,'station');

I see that the following works though now:

scnl.station

So are we okay with lack of backward compatibility?

**Comment by CelsoReyes** [comment]
Hi Glenn,
Let me take a look at it.  if anything,I might modify it to

...
try
  val = scnlobj.(prop);
catch
 ...
end

but I'm sure I've implemented something badly that I'll need to get to the
root cause of.

btw.  *eval*  should generally be avoided because there is no way that
MATLAB can tell what's happening ahead of time. Plus this version is more
readable, and works even in older versions.

**Comment by CelsoReyes** [comment]
Hm.. I was working off the main branch and had no problem with it.

>> s = scnlobject('MBLG','SHZ','NM','--')

s =

   station: MBLG
   channel: SHZ
   network: NM
  location: --

>> get(s,'station')

ans =

MBLG

**Comment by CelsoReyes** [comment]
ugh.  and I see that I used eval in several places (old code), which I will
have to update

**Comment by CelsoReyes** [comment]
because I'm already doing it in waveform, I'm going to quickly kill the
eval's everywhere I see them in GISMO (only where the change is obvious). I
figure that'd be ok?
If not, then slap me on the wrist... I won't be offended.
:)
Celso

**Comment by gthompson** [comment]
Please kill the evals. Bad legacy habit of mine.

I'm currently rebuilding the IceWeb (i.e. spectrograms) code-base on top of
our current gismotools master. I probably have evals in there too I need to
kill. I'm replacing things like

get(scnlobject, 'station')

with

scnlobject.station

as a first pass, just to get up and running. but I guess I really should be
using channeltag.

**Comment by gthompson** [comment]
I am using channeltag for everything now. Easy transition. So closing this issue.
