### ISSUE TITLE
print_debug not working correctly

### ISSUE THREAD

**Issue by gthompson** [giseislab/gismotools#59]
debug.print_debug seems to be ignoring the debug level after it was recently modified to use persistent variables.

So whether I debug.set_debug to level 0 or level 1000, every debug.print_debug message is always shown

**Comment by CelsoReyes** [comment]
Hmmm.. let me take a quick look

**Comment by CelsoReyes** [comment]
have you tried `clear functions` ?
any speedup would come from it bypassing the preference lookup every time.  The downside is that the value is saafely then is locked away until functions are cleared.

The only other place to change it would be in the print_debug function itself.  However, then it messes with way it translates directly to a fprintf function... unless... unless....
I've got it!  Modifying master. should be ready in 5 minutes

**Comment by CelsoReyes** [comment]
done. now call with
`debug.print_debug(newlevel)`
which will change the debug level to `newlevel` but won't change the default

One further modification suggestion would be to add something like
debug.print_debug() resets the level to the default ...  
OR
debug.print_debug(newlevel) changes the preferences as well.
if so, then set_debug probably becomes unneccessary

**Comment by gthompson** [comment]
Good idea to make set_debug obsolete
